### PR TITLE
Fix code block display

### PR DESCRIPTION
**Pull request by jglick**
You can indent text in Markdown to be a code block, or you can use backticks with a language, but you should not use both.

### CODE REVIEW

**Comment by jglick** [comment]
By the way I am not sure when you last tested these instructions (specifically those for workload identity), but I needed to make several modifications just for setup and it is still not working for me due to IAM issues. If I wind up sorting things out I will file a PR amending instructions.

**Comment by blackpiglet** [comment]
The issue will be fixed in #106.

**Comment by jglick** [comment]
Only partly: https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/106#pullrequestreview-1540383121

**Comment by blackpiglet** [comment]
Oh, right, but looks like only that part impacted the MarkDown display.
Although the other blocks also have the mentioned issue, they do seem not to affect the reading.

**Pull request closed without merging**
