### PR TITLE
Add support for CSI driver gcp.csi.confidential.cloud

### PR DESCRIPTION
**Pull request by ps-occrp**
Add supports for CSI driver used by [constellation](https://github.com/edgelesssys/constellation) as reported at https://github.com/vmware-tanzu/velero/issues/6470

### CODE REVIEW

**Comment by blackpiglet** [comment]
The code change looks good, but could you help to also add some test cases for the CSI driver handling change? The new UT should be added in `TestGetVolumeID` and `TestSetVolumeID` in `velero-plugin-for-gcp/volume_snapshotter_test.go`.

**Comment by ps-occrp** [comment]
@blackpiglet I have copied test cases from `pd.csi.storage.gke.io`. let me know if there should be tests specifically tailored for `gcp.csi.confidential.cloud`

**Comment by ps-occrp** [comment]
When can this be merged?

**Comment by blackpiglet** [comment]
@qiuming-best @reasonerjt 
Please help to take a look at this PR.

**Review by qiuming-best — APPROVED** [review]

**Pull request merged**
