### PR TITLE
Insufficient Role permissions in GKE setup instructions 

### PR DESCRIPTION
**Pull request by austinchambers**
This fixes https://github.com/vmware-tanzu/velero-plugin-for-gcp/issues/26

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
@austinchambers Thanks for your PR. Can you please follow the steps here https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/27/checks?check_run_id=647495820 to signoff your commits?

**Comment by austinchambers** [comment]
Ah, thanks for the heads up. Just signed off now.

**Comment by skriss** [comment]
We do have the following in Step 3 under [Set permissions](https://github.com/vmware-tanzu/velero-plugin-for-gcp#set-permissions-for-velero), which sets the relevant permissions on the individual bucket rather than the entire project:

```
gsutil iam ch serviceAccount:$SERVICE_ACCOUNT_EMAIL:objectAdmin gs://${BUCKET}
```

**Comment by austinchambers** [comment]
@skriss Oh, shoot. You're absolutely right. I somehow glanced over that the multiple times I've tried going over this guide. 

Sorry about that! I'll re-run using that step and close this out if the problem goes away.

**Comment by austinchambers** [comment]
Verified that once I ran that step, everything worked properly. Thanks and sorry about that!

**Comment by skriss** [comment]
:+1: no worries, appreciate the input regardless!

**Pull request closed without merging**
